//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLOWANCE
    {
        public int ALLOW_ID { get; set; }
        public string ALLOW_NAME { get; set; }
        public Nullable<decimal> ALLOW_AMOUNT { get; set; }
        public Nullable<decimal> ALLOW_PERCENT { get; set; }
        public string ALLOW_TYPE { get; set; }
        public Nullable<byte> ALLOW_CATEGORY { get; set; }
        public Nullable<short> MIN_HOURS { get; set; }
        public byte DEDUCT_ONABSENT { get; set; }
    }
}
