//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE_LOG
    {
        public int Emp_Id { get; set; }
        public System.DateTime TDate { get; set; }
        public string TTime { get; set; }
        public Nullable<byte> Mode { get; set; }
        public Nullable<byte> Flag { get; set; }
        public int TimeVal { get; set; }
        public Nullable<short> DeviceNo { get; set; }
        public Nullable<byte> VerifyResult { get; set; }
        public string DeviceIP { get; set; }
        public string ATTMODE { get; set; }
    }
}
