//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE
    {
        public int EMP_ID { get; set; }
        public short WORKHOUR_ID { get; set; }
        public System.DateTime TDATE { get; set; }
        public Nullable<System.DateTime> TDATE_OUT { get; set; }
        public string INTIME { get; set; }
        public string INMODE { get; set; }
        public string INREMARKS { get; set; }
        public string OUTTIME { get; set; }
        public string OUTMODE { get; set; }
        public string OUTREMARKS { get; set; }
        public string LUNCHIN { get; set; }
        public string LUNCHINMODE { get; set; }
        public string LUNCHINREMARKS { get; set; }
        public string LUNCHOUT { get; set; }
        public string LUNCHOUTMODE { get; set; }
        public string LUNCHOUTREMARKS { get; set; }
        public string TIFFININ { get; set; }
        public string TIFFININMODE { get; set; }
        public string TIFFININREMARKS { get; set; }
        public string TIFFINOUT { get; set; }
        public string TIFFINOUTMODE { get; set; }
        public string TIFFINOUTREMARKS { get; set; }
        public byte ATT_STATUS { get; set; }
        public string OUT_VNO { get; set; }
        public Nullable<byte> IS_HALTED { get; set; }
        public bool FLGIN { get; set; }
        public bool FLGOUT { get; set; }
        public Nullable<System.DateTime> DT_LOUT { get; set; }
        public Nullable<System.DateTime> DT_LIN { get; set; }
        public Nullable<System.DateTime> DT_TOUT { get; set; }
        public Nullable<System.DateTime> DT_TIN { get; set; }
    
        public virtual EMP_DETAIL EMP_DETAIL { get; set; }
        public virtual WORK_HOUR WORK_HOUR { get; set; }
    }
}
