//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_NepDate
    {
        public short BS { get; set; }
        public string IDATE { get; set; }
        public string EDATE { get; set; }
        public string Eyear { get; set; }
        public Nullable<short> C1 { get; set; }
        public Nullable<short> C2 { get; set; }
        public Nullable<short> C3 { get; set; }
        public Nullable<short> C4 { get; set; }
        public Nullable<short> C5 { get; set; }
        public Nullable<short> C6 { get; set; }
        public Nullable<short> C7 { get; set; }
        public Nullable<short> C8 { get; set; }
        public Nullable<short> C9 { get; set; }
        public Nullable<short> C10 { get; set; }
        public Nullable<short> C11 { get; set; }
        public Nullable<short> C12 { get; set; }
        public Nullable<short> Totaldays { get; set; }
    }
}
