//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEDUCTION
    {
        public int DED_ID { get; set; }
        public string DED_NAME { get; set; }
        public Nullable<decimal> DED_AMOUNT { get; set; }
        public string DED_TYPE { get; set; }
        public Nullable<decimal> DED_PERCENT { get; set; }
    }
}
