//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEFAULT_WORKHOUR
    {
        public int Emp_Id { get; set; }
        public byte DAY_ID { get; set; }
        public short WorkHour_Id { get; set; }
    
        public virtual WORK_HOUR WORK_HOUR { get; set; }
    }
}
