//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE_SETTING_MULTI
    {
        public short SettingNo { get; set; }
        public string Device_Model { get; set; }
        public string ChannelNo { get; set; }
        public byte DeviceNo { get; set; }
        public byte PortNo { get; set; }
        public int Reading_SleepTime { get; set; }
        public string IP_Address { get; set; }
        public Nullable<short> TCP_TIMEOUT { get; set; }
        public byte TotalDataLength { get; set; }
        public int MCTimer { get; set; }
        public byte ClearDevLog_Manually { get; set; }
        public string Device_DispName { get; set; }
        public long BaudRate { get; set; }
        public string Device_AttMode { get; set; }
    }
}
