//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_SALDEDUCT
    {
        public int VOUCHERID { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<double> INTEREST { get; set; }
        public Nullable<int> DURATION { get; set; }
        public Nullable<byte> SMONTH { get; set; }
        public Nullable<short> SYEAR { get; set; }
        public Nullable<System.DateTime> SDATE { get; set; }
        public Nullable<byte> EMONTH { get; set; }
        public Nullable<short> EYEAR { get; set; }
        public Nullable<System.DateTime> EDATE { get; set; }
        public Nullable<double> IPINSTALLMENT { get; set; }
        public Nullable<double> APINSTALLMENT { get; set; }
        public Nullable<double> TOTALAMOUNT { get; set; }
        public Nullable<bool> FLAG { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<short> TRN_ID { get; set; }
        public Nullable<byte> INSTALLMENT { get; set; }
        public Nullable<int> APPROVEDBYID { get; set; }
        public Nullable<bool> OPTFLAG { get; set; }
        public Nullable<double> BALANCE { get; set; }
        public Nullable<byte> PVALUE { get; set; }
        public Nullable<int> CALCDURATION { get; set; }
        public Nullable<byte> DYNSMONTH { get; set; }
        public Nullable<short> DYNSYEAR { get; set; }
        public Nullable<bool> ISBSDATE { get; set; }
    
        public virtual EMP_DETAIL EMP_DETAIL { get; set; }
        public virtual TBL_PAYMODE TBL_PAYMODE { get; set; }
        public virtual TBL_TRNTYPE TBL_TRNTYPE { get; set; }
    }
}
