//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_DETAIL
    {
        public EMP_DETAIL()
        {
            this.EMP_SALDEDUCT = new HashSet<EMP_SALDEDUCT>();
            this.ATTENDANCEs = new HashSet<ATTENDANCE>();
            this.DASHINALLOWANCE_DETAIL = new HashSet<DASHINALLOWANCE_DETAIL>();
            this.EMP_EDUTRN = new HashSet<EMP_EDUTRN>();
            this.EMP_FORCED_HOLIDAYS = new HashSet<EMP_FORCED_HOLIDAYS>();
            this.EMP_JOBLOG = new HashSet<EMP_JOBLOG>();
            this.EMP_NOK = new HashSet<EMP_NOK>();
            this.EMP_OUTSTATION = new HashSet<EMP_OUTSTATION>();
            this.EMP_TRAN = new HashSet<EMP_TRAN>();
            this.OTPAID_DETAIL = new HashSet<OTPAID_DETAIL>();
            this.OVERTIMEs = new HashSet<OVERTIME>();
            this.WEEKENDs = new HashSet<WEEKEND>();
            this.TBLJOBS = new HashSet<TBLJOB>();
        }
    
        public int EMP_ID { get; set; }
        public string EMP_TITLE { get; set; }
        public string EMP_FIRSTNAME { get; set; }
        public string EMP_MIDDLENAME { get; set; }
        public string EMP_LASTNAME { get; set; }
        public string EMP_TADD { get; set; }
        public string EMP_PADD { get; set; }
        public string EMP_TSTREET { get; set; }
        public string EMP_PSTREET { get; set; }
        public string EMP_TDISTRICT { get; set; }
        public string EMP_PDISTRICT { get; set; }
        public string EMP_TZONE { get; set; }
        public string EMP_PZONE { get; set; }
        public string EMP_TCOUNTRY { get; set; }
        public string EMP_PCOUNTRY { get; set; }
        public string EMP_CITIZENSHIPNO { get; set; }
        public string EMP_PHONE { get; set; }
        public Nullable<System.DateTime> EMP_DOB { get; set; }
        public string EMP_EDUCATION { get; set; }
        public byte[] EMP_PHOTO { get; set; }
        public string EMP_PASSWORD { get; set; }
        public string EMP_SIGNINMODE { get; set; }
        public Nullable<System.DateTime> EMP_JOINDATE { get; set; }
        public Nullable<System.DateTime> UpTo_Date { get; set; }
        public string EMP_CARDID { get; set; }
        public string EMP_MOBILE { get; set; }
        public string EMP_GENDER { get; set; }
        public string EMP_MARITALSTATUS { get; set; }
        public byte ATTBWISE { get; set; }
    
        public virtual ICollection<EMP_SALDEDUCT> EMP_SALDEDUCT { get; set; }
        public virtual ICollection<ATTENDANCE> ATTENDANCEs { get; set; }
        public virtual ICollection<DASHINALLOWANCE_DETAIL> DASHINALLOWANCE_DETAIL { get; set; }
        public virtual ICollection<EMP_EDUTRN> EMP_EDUTRN { get; set; }
        public virtual ICollection<EMP_FORCED_HOLIDAYS> EMP_FORCED_HOLIDAYS { get; set; }
        public virtual ICollection<EMP_JOBLOG> EMP_JOBLOG { get; set; }
        public virtual ICollection<EMP_NOK> EMP_NOK { get; set; }
        public virtual ICollection<EMP_OUTSTATION> EMP_OUTSTATION { get; set; }
        public virtual ICollection<EMP_TRAN> EMP_TRAN { get; set; }
        public virtual ICollection<OTPAID_DETAIL> OTPAID_DETAIL { get; set; }
        public virtual ICollection<OVERTIME> OVERTIMEs { get; set; }
        public virtual ICollection<WEEKEND> WEEKENDs { get; set; }
        public virtual ICollection<TBLJOB> TBLJOBS { get; set; }
    }
}
