//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_ALLOWANCE_COLLECTION
    {
        public long COLL_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> GENID { get; set; }
        public Nullable<int> ALLOW_ID { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> TOT_AMOUNT { get; set; }
    }
}
