//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_EDUTRN
    {
        public int Emp_Id { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string TName { get; set; }
        public byte flg { get; set; }
    
        public virtual EMP_DETAIL EMP_DETAIL { get; set; }
    }
}
