//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_NOK
    {
        public int EMP_ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string RELATION { get; set; }
    
        public virtual EMP_DETAIL EMP_DETAIL { get; set; }
    }
}
