//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_PERSONALOUT
    {
        public decimal Id { get; set; }
        public Nullable<int> Emp_Id { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public string OutTime { get; set; }
        public string OutRemarks { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string InTime { get; set; }
        public string InRemarks { get; set; }
    }
}
