//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_TRAN
    {
        public EMP_TRAN()
        {
            this.SalarySheets = new HashSet<SalarySheet>();
        }
    
        public int PID { get; set; }
        public string EMP_TRANMODE { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<short> DEG_ID { get; set; }
        public Nullable<short> MODE_ID { get; set; }
        public Nullable<int> DEPT_ID { get; set; }
        public Nullable<short> BRANCH_ID { get; set; }
        public Nullable<short> STATUS_ID { get; set; }
        public Nullable<decimal> BSALARY { get; set; }
        public Nullable<double> BTAX { get; set; }
        public Nullable<int> GRADE { get; set; }
        public Nullable<System.DateTime> JDATE { get; set; }
        public string JBSDATE { get; set; }
        public string BYDATE { get; set; }
        public bool NEGATIVELEAVE { get; set; }
        public string GENERATEDBY { get; set; }
        public string REMARKS { get; set; }
        public Nullable<byte> EMP_CATEGORY { get; set; }
        public Nullable<byte> EMP_ATTGROUP { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public string EXT { get; set; }
        public Nullable<int> CLASS { get; set; }
        public string AccountNo { get; set; }
        public byte TDSTYPE { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual DESIGNATION DESIGNATION { get; set; }
        public virtual EMP_DETAIL EMP_DETAIL { get; set; }
        public virtual EMP_LOG EMP_LOG { get; set; }
        public virtual GRADE GRADE1 { get; set; }
        public virtual MODE MODE { get; set; }
        public virtual STATUS STATUS { get; set; }
        public virtual ICollection<SalarySheet> SalarySheets { get; set; }
    }
}
