//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_LEAVE
    {
        public int PID { get; set; }
        public short LEAVEID { get; set; }
        public short DAYS { get; set; }
        public string LEAVEBY { get; set; }
        public Nullable<short> MAXDAYS { get; set; }
        public string PAID { get; set; }
        public Nullable<short> UPTOMONTH { get; set; }
        public Nullable<short> UPTOYEAR { get; set; }
        public string BYDATE { get; set; }
        public string TRNUSER { get; set; }
    
        public virtual LEAVE LEAVE { get; set; }
    }
}
