//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_ABSENTREMARKS
    {
        public int EMP_ID { get; set; }
        public System.DateTime ABS_DATE { get; set; }
        public string REMARKS { get; set; }
        public string TRNUSER { get; set; }
    }
}
