//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_OUTSTATION
    {
        public string VNO { get; set; }
        public int EMP_ID { get; set; }
        public System.DateTime TDATE { get; set; }
        public Nullable<short> DEPARTMENTID { get; set; }
        public Nullable<short> DESIGNATIONID { get; set; }
        public string STATION { get; set; }
        public System.DateTime SDATE { get; set; }
        public Nullable<System.DateTime> EDATE { get; set; }
        public Nullable<int> DAYS { get; set; }
        public string PURPOSE { get; set; }
        public int APPROVED_BY { get; set; }
        public int TMODEID { get; set; }
    
        public virtual EMP_DETAIL EMP_DETAIL { get; set; }
    }
}
