//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_FORCED_HOLIDAYS
    {
        public int Emp_id { get; set; }
        public System.DateTime HDate { get; set; }
        public string HName { get; set; }
        public byte HType { get; set; }
    
        public virtual EMP_DETAIL EMP_DETAIL { get; set; }
    }
}
