//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_TRAINING
    {
        public int Trn_Id { get; set; }
        public string TName { get; set; }
        public int TType { get; set; }
        public Nullable<decimal> TCost { get; set; }
        public Nullable<System.DateTime> TDate_From { get; set; }
        public Nullable<System.DateTime> TDate_To { get; set; }
        public string TTime_From { get; set; }
        public string TTime_To { get; set; }
        public Nullable<byte> flg { get; set; }
    
        public virtual TRAINING_TYPE TRAINING_TYPE { get; set; }
    }
}
