//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_LOG
    {
        public Nullable<System.DateTime> TDATE { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public int PID { get; set; }
    
        public virtual EMP_TRAN EMP_TRAN { get; set; }
    }
}
