//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_EXTRAFACILITY
    {
        public int EF_ID { get; set; }
        public Nullable<int> Emp_Id { get; set; }
        public string ByDate { get; set; }
        public Nullable<int> ADMonth { get; set; }
        public Nullable<int> ADYear { get; set; }
        public Nullable<int> BSMonth { get; set; }
        public Nullable<int> BSYear { get; set; }
        public string Facility_Name { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string GivenBy { get; set; }
        public Nullable<int> Ref_voucherNo { get; set; }
        public Nullable<int> APPROVEDBY { get; set; }
        public string REMARKS { get; set; }
    }
}
