//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE
    {
        public GRADE()
        {
            this.EMP_TRAN = new HashSet<EMP_TRAN>();
        }
    
        public int GRADE_ID { get; set; }
        public string GRADE_NAME { get; set; }
        public string GRADE_TYPE { get; set; }
    
        public virtual ICollection<EMP_TRAN> EMP_TRAN { get; set; }
        public virtual GRADE_TYPE GRADE_TYPE1 { get; set; }
    }
}
