//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_TYPE
    {
        public GRADE_TYPE()
        {
            this.GRADEs = new HashSet<GRADE>();
        }
    
        public string GType { get; set; }
    
        public virtual ICollection<GRADE> GRADEs { get; set; }
    }
}
