//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLIDAY
    {
        public int HOLIDAY_ID { get; set; }
        public string HOLIDAY_NAME { get; set; }
        public Nullable<System.DateTime> HOLIDAY_DATE { get; set; }
        public Nullable<decimal> HOLIDAY_QTY { get; set; }
    }
}
