//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVE
    {
        public LEAVE()
        {
            this.EMP_LEAVE = new HashSet<EMP_LEAVE>();
            this.LEAVE_LEDGER = new HashSet<LEAVE_LEDGER>();
            this.LEAVE_LEDGER_TEMP = new HashSet<LEAVE_LEDGER_TEMP>();
        }
    
        public short LEAVE_ID { get; set; }
        public string LEAVE_NAME { get; set; }
        public Nullable<int> LEAVE_DAYS { get; set; }
        public Nullable<byte> LEAVE_TYPE { get; set; }
        public Nullable<short> LEAVE_MAX { get; set; }
        public Nullable<byte> ISPAIDLEAVE { get; set; }
        public decimal LEAVE_PAY_QTY { get; set; }
    
        public virtual ICollection<EMP_LEAVE> EMP_LEAVE { get; set; }
        public virtual ICollection<LEAVE_LEDGER> LEAVE_LEDGER { get; set; }
        public virtual ICollection<LEAVE_LEDGER_TEMP> LEAVE_LEDGER_TEMP { get; set; }
    }
}
