//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVE_LEDGER_TEMP
    {
        public System.DateTime Leave_Date { get; set; }
        public int EMP_ID { get; set; }
        public Nullable<short> LEAVE_ID { get; set; }
        public Nullable<decimal> TAKEN { get; set; }
        public string REMARKS { get; set; }
        public string EnteredBy { get; set; }
        public byte IsRegular { get; set; }
        public decimal NOHRS { get; set; }
    
        public virtual LEAVE LEAVE { get; set; }
    }
}
