//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN_MODES
    {
        public byte Key_Id { get; set; }
        public string Mode_Desc { get; set; }
        public string Mode_Name { get; set; }
    }
}
