//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGVALUESETTING
    {
        public string DModel { get; set; }
        public Nullable<byte> TypeId { get; set; }
        public Nullable<decimal> DeviceNo { get; set; }
        public Nullable<decimal> ProjectNo { get; set; }
        public Nullable<decimal> DutyNo { get; set; }
        public Nullable<decimal> CardNo { get; set; }
        public Nullable<decimal> YY { get; set; }
        public Nullable<decimal> MM { get; set; }
        public Nullable<decimal> DD { get; set; }
        public Nullable<decimal> D { get; set; }
        public Nullable<decimal> Hrs { get; set; }
        public Nullable<decimal> Mins { get; set; }
        public Nullable<byte> TotalLength { get; set; }
        public Nullable<byte> CIDLength { get; set; }
        public string RefChar { get; set; }
        public string DEVICEMODE { get; set; }
        public decimal SEQNO { get; set; }
        public byte YYLen { get; set; }
        public byte SEQLen { get; set; }
        public byte DUTYNOLen { get; set; }
        public byte DEVICENOLen { get; set; }
    }
}
