//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOHOLIDAY_CONDITIONS
    {
        public string DAY1 { get; set; }
        public string DAY2 { get; set; }
        public string UPDAYS { get; set; }
        public string DOWNDAYS { get; set; }
        public bool GRANTHOLIDAY { get; set; }
    }
}
