//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPAID_DETAIL
    {
        public int Id { get; set; }
        public int Emp_ID { get; set; }
        public int Pid { get; set; }
        public decimal OTHours { get; set; }
        public Nullable<decimal> Payable { get; set; }
    
        public virtual EMP_DETAIL EMP_DETAIL { get; set; }
        public virtual OTPAID OTPAID { get; set; }
    }
}
