//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPAID
    {
        public OTPAID()
        {
            this.OTPAID_DETAIL = new HashSet<OTPAID_DETAIL>();
        }
    
        public int Id { get; set; }
        public System.DateTime TrnDate { get; set; }
        public short ForTheMonth { get; set; }
        public int Year { get; set; }
        public string ByDate { get; set; }
        public string TrnUser { get; set; }
    
        public virtual ICollection<OTPAID_DETAIL> OTPAID_DETAIL { get; set; }
    }
}
