//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarySheet
    {
        public int GenID { get; set; }
        public Nullable<System.DateTime> Edate { get; set; }
        public Nullable<int> ForTheMonth { get; set; }
        public string ByDate { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> VoucherNo { get; set; }
        public int Emp_Id { get; set; }
        public int PID { get; set; }
        public Nullable<short> ModeId { get; set; }
    
        public virtual EMP_TRAN EMP_TRAN { get; set; }
    }
}
