//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTING_PAY
    {
        public string PayrollType { get; set; }
        public Nullable<decimal> HoursPerMonth { get; set; }
        public string BSalType { get; set; }
        public Nullable<decimal> HoursPerDay { get; set; }
        public Nullable<decimal> OTCalcRate { get; set; }
        public Nullable<decimal> PF_AddPercent { get; set; }
        public byte DayCount { get; set; }
        public byte Calculate_ExtDays { get; set; }
        public byte SELF_OTINOUT { get; set; }
        public byte HolidayCount_Mode { get; set; }
        public byte PayableDayCount_Mode { get; set; }
        public Nullable<decimal> Hrs_HalfDaypay { get; set; }
        public Nullable<decimal> Hrs_OneDaypay { get; set; }
        public byte OTCalculation_Mode { get; set; }
        public byte ExtraHoursAsOT_Mode { get; set; }
        public byte DEDUCT_ABS_ON_BSAL { get; set; }
        public byte FIXEDDAYS_IN_MONTH { get; set; }
        public byte MONTHLY_BASICHRS_MODE { get; set; }
        public byte ALLOWANCE_DED_MODE { get; set; }
        public byte ShowHrsMoreThanBasicHrsAsOT { get; set; }
        public byte SALARYSHEET_MODEWISE { get; set; }
        public byte DEDUCT_LESSHRS_AS_ABSENT { get; set; }
    }
}
