//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTING
    {
        public bool ISFPRINT { get; set; }
        public Nullable<short> SecurityLevel { get; set; }
        public Nullable<byte> WeekEndSetting { get; set; }
        public Nullable<int> WeekEndDays { get; set; }
        public short LoginMode { get; set; }
        public byte IsLogOutCheck { get; set; }
        public byte AllowLogOut_AnyTime { get; set; }
        public bool AllowSignIn_In_WEnd { get; set; }
        public bool Allow_LT_In_AnyTime { get; set; }
        public bool Absent_If_Not_SignOut { get; set; }
        public Nullable<byte> AllowLogIn_AnyTime { get; set; }
        public bool AllowSignIn_In_Leave { get; set; }
        public byte ScaleFrom { get; set; }
        public byte ScaleTo { get; set; }
        public byte LockTM { get; set; }
        public byte AllHolidays_Weekends { get; set; }
        public byte AllowFreeScan { get; set; }
        public byte AskLateInRem { get; set; }
        public byte AskOOutRem { get; set; }
        public byte AskPOutRem { get; set; }
        public byte AllowSelf_FAtt { get; set; }
        public byte AllowDynamicWH { get; set; }
        public byte CardMode { get; set; }
        public byte ReadCardLocked { get; set; }
        public byte CardType { get; set; }
        public byte AskEarlyInRem { get; set; }
        public byte AskLateOutRem { get; set; }
        public byte AskEarlyOutRem { get; set; }
        public byte ShowForm { get; set; }
        public byte BatchAtt_DateLock { get; set; }
        public string DeviceModel { get; set; }
        public byte ShowLogReports { get; set; }
        public byte CardMapped { get; set; }
        public byte Free_KeyMode { get; set; }
        public byte ShowSftSel { get; set; }
        public byte Show_DiffColors { get; set; }
        public string BackupPath { get; set; }
        public string LEAVE_GRANT_MODE { get; set; }
        public string Attendance_Mode { get; set; }
        public byte AllowJobInJobOut { get; set; }
        public byte RETRIEVE_IN_FROMANY { get; set; }
        public byte RETRIEVE_OUT_FROMANY { get; set; }
        public byte SHOW_PAYINFO { get; set; }
        public byte BRANCHWISE_REPORTS { get; set; }
        public byte ALLOWBOTH_LUNCHTIFFIN { get; set; }
        public byte AutoDeptId { get; set; }
        public byte SELECTSHIFT_INFA { get; set; }
        public byte ALLOW_INOUT_TIME_CHANGE { get; set; }
        public byte RETRIEVEIN_WEND { get; set; }
        public byte RETRIEVEIN_LEAVE { get; set; }
        public byte RETRIEVEIN_TRAVEL { get; set; }
        public byte VALIDATE_LOGOUT { get; set; }
        public string DTFORMAT { get; set; }
        public byte AUTOTRAVELID { get; set; }
        public byte IS24HRS_VALID { get; set; }
        public byte TRACK_WEEKEND_HISTORY { get; set; }
        public byte ATTFORM_FSCREEN { get; set; }
        public byte AUTO_LUNCHOUT { get; set; }
        public string AUTOLUNCHOUT_TIME { get; set; }
        public byte VALIDATE_LOGOUT_POUT { get; set; }
        public byte VALIDATE_LOGOUT_OOUT { get; set; }
        public byte OUTTIME_CHANGE_PER_WHRS { get; set; }
        public byte ATTLOCK_BRANCHWISE { get; set; }
        public byte DEVICE_BRANCHWISE { get; set; }
        public byte GET_CONTSERVERDT { get; set; }
        public byte MULTI_DEVICE_SUPPORT { get; set; }
        public string MULTI_DEVICE_ATTMODE { get; set; }
        public short LOCK_APPROVEDBY { get; set; }
        public long VALIDDUTYHRS { get; set; }
        public byte ATTMODE_DEVICEWISE { get; set; }
        public byte KEYONLYATTMODE_DAYNIGHT { get; set; }
        public byte INKEYPOWER { get; set; }
        public byte TRAVEL_ATTMODE { get; set; }
        public byte OUTBRANCH_ATTMODE { get; set; }
        public byte USER_BDAUTHORITY { get; set; }
        public byte HOURS_DISP_WITHLABEL { get; set; }
        public string EMPTRANMODE { get; set; }
        public byte EXTDAYCOUNT_CHANGE { get; set; }
        public byte VALIDATE_LOGOUT_LOUT { get; set; }
        public byte VALIDATE_LOGOUT_TOUT { get; set; }
        public byte AskOInRem { get; set; }
        public byte AskPInRem { get; set; }
    }
}
