//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_COL_SETTING
    {
        public string ReportName { get; set; }
        public string ColTitle { get; set; }
        public bool ColShow { get; set; }
        public byte ColNo { get; set; }
        public Nullable<int> ColWidth { get; set; }
        public bool Set { get; set; }
        public string SS_ColCat { get; set; }
        public Nullable<int> ACCID { get; set; }
        public bool Sum_Col { get; set; }
        public bool Calc_Col { get; set; }
    }
}
