//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS
    {
        public STATUS()
        {
            this.EMP_TRAN = new HashSet<EMP_TRAN>();
        }
    
        public short STATUS_ID { get; set; }
        public string STATUS_NAME { get; set; }
    
        public virtual ICollection<EMP_TRAN> EMP_TRAN { get; set; }
    }
}
