//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PAYMODE
    {
        public TBL_PAYMODE()
        {
            this.EMP_SALDEDUCT = new HashSet<EMP_SALDEDUCT>();
        }
    
        public byte PVALUE { get; set; }
        public string PMODE { get; set; }
    
        public virtual ICollection<EMP_SALDEDUCT> EMP_SALDEDUCT { get; set; }
    }
}
