//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpPersonalOutsMnu
    {
        public int Emp_id { get; set; }
        public byte mnuLOut { get; set; }
        public byte mnuTOut { get; set; }
        public byte mnuOOut { get; set; }
        public byte mnuPOut { get; set; }
    }
}
