//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEMP_DELETED
    {
        public int Emp_id { get; set; }
        public string DeletedBy { get; set; }
        public System.DateTime DeletedOnDT { get; set; }
        public string DeletedOnTM { get; set; }
    }
}
