//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHRSCALCULATION
    {
        public string frmName { get; set; }
        public byte DeductFullLT { get; set; }
        public byte DeductExtraLT { get; set; }
        public byte DeductPOut { get; set; }
        public byte DeductOOut { get; set; }
        public byte DeductFullTT { get; set; }
        public byte DeductExtraTT { get; set; }
        public byte DEDUCTMAXLUNCH { get; set; }
        public byte DEDUCTMAXTIFFIN { get; set; }
    }
}
