//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblINOUT_CONDITIONS
    {
        public int C_Id { get; set; }
        public string Start_Time { get; set; }
        public string End_Time { get; set; }
        public string Replace_Time { get; set; }
        public byte Flag { get; set; }
    }
}
