//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLJOB
    {
        public TBLJOB()
        {
            this.EMP_JOBLOG = new HashSet<EMP_JOBLOG>();
            this.EMP_DETAIL = new HashSet<EMP_DETAIL>();
        }
    
        public string JobId { get; set; }
        public string JobDesc { get; set; }
        public Nullable<decimal> AllotedHrs { get; set; }
        public Nullable<System.DateTime> JobStartDate { get; set; }
        public Nullable<System.DateTime> JobEndDate { get; set; }
        public byte IsCompleted { get; set; }
        public string EnteredBy { get; set; }
        public byte JOBTYPE { get; set; }
    
        public virtual ICollection<EMP_JOBLOG> EMP_JOBLOG { get; set; }
        public virtual ICollection<EMP_DETAIL> EMP_DETAIL { get; set; }
    }
}
