//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeaveDelete_Log
    {
        public long EmpId { get; set; }
        public short LeaveId { get; set; }
        public decimal LeaveQty { get; set; }
        public System.DateTime tdate { get; set; }
        public string DeletedBy { get; set; }
        public string Remarks { get; set; }
        public string DelMonth { get; set; }
    }
}
