//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOTHERDB
    {
        public string SERVERNM { get; set; }
        public string DATABASENM { get; set; }
        public string DATABASEALIAS { get; set; }
        public string USERNM { get; set; }
        public string DBUSERPWD { get; set; }
        public byte ACCESSMODE { get; set; }
    }
}
