//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemLog
    {
        public string UserName { get; set; }
        public System.DateTime LDate { get; set; }
        public string LTime { get; set; }
        public string flg { get; set; }
    }
}
