//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUSER
    {
        public tblUSER()
        {
            this.USERRIGHTS = new HashSet<USERRIGHT>();
        }
    
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<byte> ISACTIVE { get; set; }
        public string USERCATEGORY { get; set; }
        public byte INOUT_TM_CHANGE { get; set; }
        public byte REFRESH_ATT { get; set; }
        public int EMP_ID { get; set; }
        public byte EXTDAY_CHANGE_RIGHT { get; set; }
    
        public virtual ICollection<USERRIGHT> USERRIGHTS { get; set; }
    }
}
