//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_TYPE
    {
        public TRAINING_TYPE()
        {
            this.EMP_TRAINING = new HashSet<EMP_TRAINING>();
        }
    
        public int TrnType_Id { get; set; }
        public string TrnType { get; set; }
    
        public virtual ICollection<EMP_TRAINING> EMP_TRAINING { get; set; }
    }
}
