//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERRIGHT
    {
        public int UserId { get; set; }
        public Nullable<byte> A { get; set; }
        public Nullable<byte> A1 { get; set; }
        public Nullable<byte> A1A { get; set; }
        public Nullable<byte> A2 { get; set; }
        public Nullable<byte> A2A { get; set; }
        public Nullable<byte> A3 { get; set; }
        public Nullable<byte> A4 { get; set; }
        public Nullable<byte> B { get; set; }
        public Nullable<byte> B1 { get; set; }
        public Nullable<byte> B1A { get; set; }
        public Nullable<byte> B2 { get; set; }
        public Nullable<byte> B3 { get; set; }
        public Nullable<byte> B4 { get; set; }
        public Nullable<byte> B5 { get; set; }
        public Nullable<byte> B6 { get; set; }
        public Nullable<byte> B7 { get; set; }
        public Nullable<byte> B8 { get; set; }
        public Nullable<byte> B9 { get; set; }
        public Nullable<byte> B9A { get; set; }
        public Nullable<byte> B10 { get; set; }
        public Nullable<byte> B11 { get; set; }
        public Nullable<byte> B11A { get; set; }
        public Nullable<byte> B12 { get; set; }
        public Nullable<byte> B13 { get; set; }
        public Nullable<byte> B13A { get; set; }
        public Nullable<byte> B14 { get; set; }
        public Nullable<byte> B15 { get; set; }
        public Nullable<byte> B16 { get; set; }
        public Nullable<byte> C { get; set; }
        public Nullable<byte> C1 { get; set; }
        public Nullable<byte> C1A { get; set; }
        public Nullable<byte> C2 { get; set; }
        public Nullable<byte> C3 { get; set; }
        public Nullable<byte> C3A { get; set; }
        public Nullable<byte> C4 { get; set; }
        public Nullable<byte> C5 { get; set; }
        public Nullable<byte> C6 { get; set; }
        public Nullable<byte> C6A { get; set; }
        public Nullable<byte> C7 { get; set; }
        public Nullable<byte> C8 { get; set; }
        public Nullable<byte> C8A { get; set; }
        public Nullable<byte> C9 { get; set; }
        public Nullable<byte> C10 { get; set; }
        public Nullable<byte> C11 { get; set; }
        public Nullable<byte> C12 { get; set; }
        public Nullable<byte> C13 { get; set; }
        public Nullable<byte> C11A { get; set; }
        public Nullable<byte> C14 { get; set; }
        public Nullable<byte> C15 { get; set; }
        public Nullable<byte> C15A { get; set; }
        public Nullable<byte> C16 { get; set; }
        public Nullable<byte> C17 { get; set; }
        public Nullable<byte> C17A { get; set; }
        public Nullable<byte> C18 { get; set; }
        public Nullable<byte> C18A { get; set; }
        public Nullable<byte> C19 { get; set; }
        public Nullable<byte> C19A { get; set; }
        public Nullable<byte> C20 { get; set; }
        public Nullable<byte> C21 { get; set; }
        public Nullable<byte> C22 { get; set; }
        public Nullable<byte> C23 { get; set; }
        public Nullable<byte> C24 { get; set; }
        public Nullable<byte> C23A { get; set; }
        public Nullable<byte> C25 { get; set; }
        public Nullable<byte> C26 { get; set; }
        public Nullable<byte> C27 { get; set; }
        public Nullable<byte> D { get; set; }
        public Nullable<byte> D1 { get; set; }
        public Nullable<byte> D2 { get; set; }
        public Nullable<byte> D3 { get; set; }
        public Nullable<byte> D3A { get; set; }
        public Nullable<byte> D4 { get; set; }
        public Nullable<byte> D5 { get; set; }
        public Nullable<byte> D5A { get; set; }
        public Nullable<byte> D6 { get; set; }
        public Nullable<byte> D7 { get; set; }
        public Nullable<byte> D7A { get; set; }
        public Nullable<byte> D8 { get; set; }
        public Nullable<byte> D9 { get; set; }
        public Nullable<byte> D10 { get; set; }
        public Nullable<byte> D11 { get; set; }
        public Nullable<byte> D12 { get; set; }
        public Nullable<byte> D12A { get; set; }
        public Nullable<byte> D13 { get; set; }
        public Nullable<byte> D14 { get; set; }
        public Nullable<byte> D14A { get; set; }
        public Nullable<byte> D15 { get; set; }
        public Nullable<byte> D16 { get; set; }
        public Nullable<byte> D16A { get; set; }
        public Nullable<byte> D17 { get; set; }
        public Nullable<byte> D18 { get; set; }
        public Nullable<byte> D19 { get; set; }
        public Nullable<byte> D20 { get; set; }
        public Nullable<byte> D20A { get; set; }
        public Nullable<byte> D21 { get; set; }
        public Nullable<byte> D22 { get; set; }
        public byte D22A { get; set; }
        public byte D23 { get; set; }
        public byte D24 { get; set; }
        public byte D25 { get; set; }
        public Nullable<byte> E { get; set; }
        public Nullable<byte> E1 { get; set; }
        public Nullable<byte> E2 { get; set; }
        public Nullable<byte> E2A { get; set; }
        public Nullable<byte> E3 { get; set; }
        public Nullable<byte> M { get; set; }
        public Nullable<byte> M1 { get; set; }
        public Nullable<byte> M2 { get; set; }
        public Nullable<byte> M3 { get; set; }
        public byte D25A { get; set; }
        public byte D26 { get; set; }
        public byte D27 { get; set; }
        public byte D28A { get; set; }
        public byte D29 { get; set; }
        public byte D30 { get; set; }
        public byte D31 { get; set; }
        public byte C28 { get; set; }
        public byte C29 { get; set; }
        public byte C30 { get; set; }
        public byte E3A { get; set; }
        public byte E4 { get; set; }
        public byte D32 { get; set; }
        public byte D9A { get; set; }
        public byte C16A { get; set; }
        public byte C34 { get; set; }
        public byte D33 { get; set; }
        public byte C31A { get; set; }
        public byte C31 { get; set; }
        public byte C32 { get; set; }
        public byte C33 { get; set; }
        public byte D34 { get; set; }
        public byte C35 { get; set; }
        public byte C36 { get; set; }
        public byte C36A { get; set; }
        public byte C37 { get; set; }
        public byte D35 { get; set; }
        public byte C38 { get; set; }
        public byte B17 { get; set; }
        public byte D36 { get; set; }
    
        public virtual tblUSER tblUSER { get; set; }
    }
}
